title: CodeNginx
subtitle: Coding like Nginx
link: http://www.codenginx.org
meta:
  description: coding like Nginx 
  keywords: !!seq
    - nginx
    - web browser
    - network optimize
    - chromium
    - http/2
    - quic
    - git
    - adblock
  author: 陈礼军 
master:
  name: 陈礼军 
  about: 向Nginx致敬！跟自己过不去的程序猿才是好工程师！
  email: stevenchen20021@gmail.com
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner:
    begin: CodeNginx
    content: 浙ICP备15016680号-1
    href: http://www.miibeian.gov.cn
    end: 在线
  beginYear: 2015
  endYear: 2015
theme: default
codetheme: night
